import { describe, expect, it } from 'vitest';
import { createPublicId, isPublicId } from './public-id';

const TODO_TEST_PUBLIC_ID = '00000000-0000-4000-8000-000000000000';

describe('public IDs', () => {
	it('accepts a canonical lowercase UUIDv4', () => {
		expect(isPublicId(TODO_TEST_PUBLIC_ID)).toBe(true);
	});

	it('accepts IDs generated by createPublicId', () => {
		expect(isPublicId(createPublicId())).toBe(true);
	});

	it.each([
		['uppercase hexadecimal', '00000000-0000-4000-8000-00000000000A'],
		['a different UUID version', '00000000-0000-3000-8000-000000000000'],
		['a different UUID variant', '00000000-0000-4000-7000-000000000000'],
		['missing separators', '00000000000040008000000000000000'],
		['non-UUID text', 'TODO_INVALID_PUBLIC_ID'],
		['a non-string value', null]
	])('rejects %s', (_description, value) => {
		expect(isPublicId(value)).toBe(false);
	});
});
